name: SafeFamily APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Compilar con Buildozer oficial
        run: |
          docker pull ghcr.io/kivy/buildozer:latest

          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            -v "$HOME/.buildozer":/home/user/.buildozer \
            ghcr.io/kivy/buildozer:latest \
            android debug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: SafeFamily-APK
          path: bin/*.apk
          if-no-files-found: error